version: 1.0.0.{build}
image: Visual Studio 2017

skip_tags: true

configuration: Release

platform: x64

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'


build:
  verbosity: minimal

artifacts:
- path: CM3D2x64_Launcher\bin\Release\CM3D2x64_Launcher.exe
  name: CM3D2x64 Launcher
- path: ARGDisplayer\bin\x64\Release\ARGDisplayer.exe
  name: Arguments Displayer
- path: ArLib.Logger\bin\Release\ArLib.Logger.dll
  name: ArHShRn Library Logger
- path: ArLib.Logger\bin\Release\ArLib.Logger.xml
  name: ArHShRn Library Logger XML

deploy:
- provider: GitHub
  tag: v$(appveyor_build_version)
  release: Misc_Collections-v$(appveyor_build_version)
  auth_token:
    secure: 9A9cpAgA6HOpTiGLt1cnLLR8CddU9/P2qxaiL6LNMmU5cKaXoncdru/CvxLar+jM
  artifact: /.*/
  prerelease: false

notifications:
- provider: Email
  to:
  - drancickphysix@yahoo.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
